version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - printenv

  build:
    on-failure: ABORT
    commands:
      - echo Start build ...

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - echo COMMIT_HASH $COMMIT_HASH
      - echo REPOSITORY_URL $REPOSITORY_URL

      - echo Build started on `date`
      - echo Building the Docker image...

      - docker build -t $REPOSITORY_URL:latest -f Dockerfile .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$COMMIT_HASH

      - echo Build completed on `date`
      - echo Pushing the Docker image...

      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$COMMIT_HASH

      - printf '[{"imageUri":"%s", "name":"%s"}]' $REPOSITORY_URL:$COMMIT_HASH $BACKEND_CONTAINER_NAME > backend_imagedefinitions.json
      - echo Build done

artifacts:
  files:
    - backend_imagedefinitions.json